### ISSUE TITLE
Time to merge calculation

### ISSUE THREAD

**Issue by maiqueb** [kubevirt/ci-health#28]
I wonder about this metric; shouldn't it take into account the PRs currently ready but not being merged ? 

Imagine this very disastrous scenario: a single PR in the queue, trying to be merged for the last 20 days.

iiuc, your metrics would mislead us into thinking all is OK.

Just a thought I had about this; you can dismiss it and close it if you feel this is a bad idea.

**Comment by fgimenez** [comment]
Good catch, currently a PR that stays for a long time in the queue affects the merge queue length metric while it hasn't been merged and the time to merge after it has been merged. So, as they are defined, the merge queue length gives information about the live queue at any point in time and the time to merge informs about the past performance, PRs already merged.

I think it might make sense to include an additional metric to take into account the cases you mention, something like time in queue, wdyt?

**Comment by maiqueb** [comment]
> Good catch, currently a PR that stays for a long time in the queue affects the merge queue length metric while it hasn't been merged and the time to merge after it has been merged. So, as they are defined, the merge queue length gives information about the live queue at any point in time and the time to merge informs about the past performance, PRs already merged.
> 
> I think it might make sense to include an additional metric to take into account the cases you mention, something like time in queue, wdyt?

Nice, works for me.

Thanks for this useful tool btw.
